pytorch fundamentals
resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.5.1+cu124


tensors- main building block- represent N-dimensional data
Pytorch tensors are created using torch.tensor()

In [ ]:
#scalar
scalar= torch.tensor(2)
scalar

tensor(2)

In [ ]:
#dimensions of scalar
scalar.ndim

0

In [ ]:
#get scalar as python int
scalar.item()

2

In [ ]:
#vector
vector= torch.tensor([2,2])
vector

tensor([2, 2])

In [ ]:
#dimension- shortcut(remember number of pairs of brackets)
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX= torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR= torch.tensor([[[1,2,3],
                       [2,5,4],
                       [3,6,9]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 5, 4],
         [3, 6, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
Tensor_prac=torch.tensor([[[[1,2,3],
                            [4,5,6],
                             [5,6,7]]]])
Tensor_prac

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [5, 6, 7]]]])

In [ ]:
Tensor_prac.ndim

4

In [ ]:
Tensor_prac.shape

torch.Size([1, 1, 3, 3])

In [ ]:
scalar.shape

torch.Size([])

### Random tensors
Random tensors are important because the way many neural networks learn is that they start with random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [ ]:
## Random  tensors - create a random tensor of size (3,4)
random_tensor= torch.rand(3,4)
random_tensor

tensor([[0.8602, 0.6322, 0.7846, 0.2617],
        [0.9706, 0.4726, 0.7809, 0.2112],
        [0.9366, 0.2068, 0.2465, 0.9018]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor_2= torch.rand(2,3)
random_tensor_2

tensor([[0.7908, 0.9678, 0.3927],
        [0.6306, 0.2437, 0.8623]])

In [ ]:
random_tensor_2.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) # height, width, color channels(RGB)
random_image_size_tensor.ndim

3

In [ ]:
random_image_size_tensor

tensor([[[0.4172, 0.4562, 0.7333],
         [0.1740, 0.1592, 0.4786],
         [0.1865, 0.0666, 0.7075],
         ...,
         [0.1042, 0.7565, 0.6489],
         [0.2640, 0.3013, 0.8477],
         [0.2380, 0.5476, 0.1555]],

        [[0.8955, 0.4876, 0.5577],
         [0.4914, 0.5604, 0.2524],
         [0.9871, 0.4883, 0.9760],
         ...,
         [0.5635, 0.5588, 0.4444],
         [0.2724, 0.7480, 0.4232],
         [0.9190, 0.5116, 0.1560]],

        [[0.6272, 0.7324, 0.9202],
         [0.5591, 0.6860, 0.5825],
         [0.9889, 0.2348, 0.5687],
         ...,
         [0.4805, 0.3487, 0.3047],
         [0.0824, 0.6130, 0.7000],
         [0.7544, 0.5959, 0.5311]],

        ...,

        [[0.1829, 0.6735, 0.6380],
         [0.7488, 0.1586, 0.6024],
         [0.4917, 0.4440, 0.2402],
         ...,
         [0.3440, 0.1309, 0.2249],
         [0.5331, 0.1515, 0.0471],
         [0.6563, 0.5209, 0.0600]],

        [[0.7412, 0.2156, 0.0174],
         [0.3763, 0.3121, 0.9444],
         [0.

In [ ]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### zeros and ones

In [ ]:
### zeros and ones
zero=torch.zeros(2,3)

In [ ]:
zero

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones= torch.ones(3,4)

In [ ]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
#dtype- defines the data type

In [ ]:
random_tensor.dtype

torch.float32

### creating a range of tensors and tensors-like

In [ ]:
 # use torch.arange()
torch.range(1,5)

<ipython-input-35-b274777fc793>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,5)


tensor([1., 2., 3., 4., 5.])

In [ ]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(1,20,2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
num=torch.arange(start=10,end=100,step=10)

In [ ]:
 # creating tensors like-  torch.zeros_like(input) creates a tensor of the same input dimension with all elements as 0
num.ndim


1

In [ ]:
num_copy=torch.zeros_like(num)
num_copy

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatypes

In [ ]:
# float 32
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, # data type of tensor
                             device="cpu", #incase of gpu - "cuda"
                             requires_grad=False) # if we want pytorch to track gradients during calculations with this tensors
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

single precision is float32, half precision is float16 and they represent how much detail a single number is stored in memory.

**tensor datatypes is one of the 3 big errors we will run in pytorch**
1. tensors not right datatype
2. tensors not right shape
3. tensors nor right device

In [ ]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor=torch.tensor([2,3,4],dtype=torch.int32)
int_32_tensor

tensor([2, 3, 4], dtype=torch.int32)

In [ ]:
product_tensor=int_32_tensor * float_32_tensor
product_tensor

tensor([ 6., 18., 36.])

In [ ]:
product_tensor.dtype

torch.float32

In [ ]:
long_tensor=torch.tensor([2,3,4],dtype=torch.long)
long_tensor

tensor([2, 3, 4])

In [ ]:
long_tensor*float_16_tensor

tensor([ 6., 18., 36.], dtype=torch.float16)

**Tensor details**


to get details from tensors


1.tensors not right datatype- to get use torch.dtype
2.tensors not right shape- to get tensor.shape
3.tensors nor right device - to get use tensor.device

In [ ]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.7181, 0.8692, 0.7716, 0.5891],
        [0.6776, 0.6260, 0.8719, 0.7802],
        [0.9252, 0.6880, 0.4243, 0.8785]])

In [ ]:
print(some_tensor)
print(f"the datatype of tensor is {some_tensor.dtype}")
print(f"the shape of tensor is {some_tensor.shape}")
print(f"the device is {some_tensor.device}")

tensor([[0.7181, 0.8692, 0.7716, 0.5891],
        [0.6776, 0.6260, 0.8719, 0.7802],
        [0.9252, 0.6880, 0.4243, 0.8785]])
the datatype of tensor is torch.float32
the shape of tensor is torch.Size([3, 4])
the device is cpu


In [ ]:
# attributes written without (), tensor.shape,
# functions written with (), .shape and .size() give same output
print(some_tensor.size())

torch.Size([3, 4])


In [ ]:
#some_tensor=some_tensor.to("cuda") to change device

### Manipulating tensors

**tensor operations include:**
1. add
2. subtract
3. multiplication (element- wise)
4. division
5. matrix multiplication

In [ ]:
# create a tensor
tensor1= torch.tensor([2,3,4])
tensor1+20

tensor([22, 23, 24])

In [ ]:
#multiply by 10
tensor1*10

tensor([20, 30, 40])

In [ ]:
tensor1

tensor([2, 3, 4])

In [ ]:
#subtract
tensor1 - 10

tensor([-8, -7, -6])

In [ ]:
# pytorch inbuilt functions
torch.mul(tensor1,10)

tensor([20, 30, 40])

In [ ]:
torch.add(tensor1,10)

tensor([12, 13, 14])

### Matrix multiplication

2 ways of doing it in neural networks
1. element wise mul
2. matrix multiplication(dot product)

there are 2 rules for performing matrix mul:
**@** refers to matrix multiplication
1. the **inner dimension** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
*  `(3,2) @ (2,3)` will work

3. the resulting shape is of the **outer dimensions**


In [ ]:
# element wise
tensor=torch.tensor([1,2,3],dtype=torch.float32)
print(tensor * tensor)

tensor([1., 4., 9.])


In [ ]:
tensor.shape

torch.Size([3])

In [ ]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14.)

In [ ]:
#matrix mul by hand
1*1+2*2+3*3

14

In [ ]:
#used to get computation time use %%time to find time
%%time
value=0
for i in range(len(tensor)):
  value+= tensor[i] + tensor[i]
print(value)

tensor(12.)
CPU times: user 2.28 ms, sys: 0 ns, total: 2.28 ms
Wall time: 2.42 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 567 µs, sys: 0 ns, total: 567 µs
Wall time: 464 µs


tensor(14.)

In [ ]:
print(len(tensor))

3


In [ ]:
tensor @ tensor

tensor(14.)

In [ ]:
# inner and outer dim
a= torch.matmul(torch.rand(3,4),torch.rand(4,5)) # outer dimension is (3,5)
a

tensor([[1.5821, 1.0735, 0.8294, 1.7060, 2.0463],
        [0.7104, 0.3319, 0.3497, 0.6687, 0.6467],
        [1.5491, 1.0246, 0.8777, 1.2622, 1.7926]])

### shape errors -  one of the most common dl errors

In [ ]:
#shapes for matrix mul
tensor_A= torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B=torch.tensor([[7,10],[8,11],[9,12]])
torch.mm(tensor_A,tensor_B) #torch.mm is same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(5,5),torch.rand(5,5))

tensor([[2.0985, 2.0242, 0.9395, 1.9685, 1.7354],
        [1.3614, 1.4595, 0.7017, 1.3643, 1.0638],
        [2.0218, 2.2151, 1.0519, 1.9143, 1.6603],
        [1.3158, 1.0871, 0.4014, 1.1094, 0.8639],
        [2.1163, 2.6106, 1.2108, 2.2684, 1.9681]])

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### to fix out tensor shape issues we can manipulate,the shape of one of them using transpose .

### **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
tensor_B.shape

torch.Size([3, 2])

In [ ]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [ ]:
tensor_A.matmul(tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
print(f"Original shape: tensor_A = {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"the new shape is : {tensor_A.shape}, tensor_B:{tensor_B.T.shape}")
print(f"multiplying:{tensor_A} @ {tensor_B.T}")
print(f"output:\n")
output= tensor_A.matmul(tensor_B.T)
print(output)
print(f"\nOutput shape:{output.shape}")

Original shape: tensor_A = torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
the new shape is : torch.Size([3, 2]), tensor_B:torch.Size([2, 3])
multiplying:tensor([[1, 2],
        [3, 4],
        [5, 6]]) @ tensor([[ 7,  8,  9],
        [10, 11, 12]])
output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape:torch.Size([3, 3])


In [ ]:
tensor_A.T.matmul(tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [ ]:
mat1= torch.rand(5,6)
mat2=torch.rand(6,7)

In [ ]:
mat1,mat2

(tensor([[0.7458, 0.5845, 0.9474, 0.6028, 0.8316, 0.7475],
         [0.4693, 0.9565, 0.8307, 0.8163, 0.7516, 0.4556],
         [0.0769, 0.6846, 0.5382, 0.9918, 0.2234, 0.6030],
         [0.8710, 0.9284, 0.9016, 0.2213, 0.7606, 0.0476],
         [0.9499, 0.0737, 0.0500, 0.9707, 0.2429, 0.5785]]),
 tensor([[0.0656, 0.5425, 0.9358, 0.2551, 0.5448, 0.1498, 0.6923],
         [0.1468, 0.7904, 0.5915, 0.5819, 0.6228, 0.2962, 0.0690],
         [0.7492, 0.6270, 0.5776, 0.8302, 0.9014, 0.1570, 0.9302],
         [0.8445, 0.6455, 0.5023, 0.2787, 0.9826, 0.9275, 0.5558],
         [0.6156, 0.9243, 0.0919, 0.0232, 0.5931, 0.5259, 0.9667],
         [0.9073, 0.9608, 0.6683, 0.7047, 0.5557, 0.7756, 0.6323]]))

In [ ]:
mat1.mm(mat2)

tensor([[2.5438, 3.3365, 2.4695, 2.0310, 3.1251, 2.0098, 3.0495],
        [2.3590, 3.1907, 2.2682, 1.9320, 3.1011, 1.9897, 2.6319],
        [2.0310, 2.3463, 1.7094, 1.5714, 2.3955, 1.8039, 1.7495],
        [1.5673, 2.6632, 2.0978, 1.6238, 2.5603, 1.1892, 2.3940],
        [1.6049, 2.0119, 1.8579, 1.0106, 2.0279, 1.6488, 1.8494]])

### tensor aggregation findind the max, min, sum

In [ ]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find the min
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
#find the max
x.max(),
torch.max(x)

tensor(90)

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
# find the mean - works for float32
torch.mean(x.type(torch.float32)) #mean works only for floating point

tensor(45.)

In [ ]:
 # find the sum
torch.sum(x)

tensor(450)

In [ ]:
x.sum()

tensor(450)

In [ ]:
#finding the positional min and max in tensor that has the minimum value
# returns an index position
x.argmin()

tensor(0)

In [ ]:
x.argmax() #max position in index 9

tensor(9)

### Reshaping Stacking and Squeezing and Unsqueezing
* Reshaping- rehsapes an input tensor to defined shape
* View- return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* stacking- combine multiple tensors on top of one another
* squeeze -  removes all `1` dimensions from a tensor
* unsqueeze -  add a `1` to target tensor
* permute- return a view of the tensor with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x= torch.arange(1.,11.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# reshape- add an extra dimension
#x_reshaped= x.reshape(1,7) #throws an error
x_reshaped= x.reshape(1,10)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
x_reshaped = x.reshape(10,1)
x_reshaped

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [ ]:
x_reshaped=x.reshape(5,2)
x_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
x_reshaped=x.reshape(2,5)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [ ]:
y=torch.arange(1.,10.)

In [ ]:
y.shape

torch.Size([9])

In [ ]:
y_reshaped= y.reshape(1,9)
y_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
y_reshaped_1=y.reshape(9,1)
y_reshaped_1

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
y_reshaped_2= y.reshape(3,3)
y_reshaped_2

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# change the view
z=x.view(1,10) #view(size)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
w= y.view(1,9)
w,y

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
w[:,0]=5
w,y

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# changing z changes x (because view of the tensor shares the same memory as the original input)
z[:,0]=8
z,x

(tensor([[ 8.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 8.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

Use of torch.stack-
https://stackoverflow.com/questions/69220221/use-of-torch-stack

In [ ]:
#stack tensors on top of each other
x_stacked= torch.stack([x,x,x]) #optional-dim=0)
x_stacked

tensor([[ 8.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 8.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 8.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
#torch.squeeze-  removes all single dimension from a target tensor
b= torch.rand(1,3,5)
b

tensor([[[0.3375, 0.9730, 0.9775, 0.7002, 0.4666],
         [0.9022, 0.7481, 0.7502, 0.2330, 0.8010],
         [0.3486, 0.5391, 0.0086, 0.1411, 0.8849]]])

In [ ]:
b.size()

torch.Size([1, 3, 5])

In [ ]:
b.squeeze()

tensor([[0.3375, 0.9730, 0.9775, 0.7002, 0.4666],
        [0.9022, 0.7481, 0.7502, 0.2330, 0.8010],
        [0.3486, 0.5391, 0.0086, 0.1411, 0.8849]])

In [ ]:
#torch squeeze
print(f"Previous tensor: {b}")
print(f"previous shape: {b.shape}")
print(f"tensor after squeezing: {b.squeeze()}")
print(f"tensor shape after squeezing: {b.squeeze().shape}")

Previous tensor: tensor([[[0.3375, 0.9730, 0.9775, 0.7002, 0.4666],
         [0.9022, 0.7481, 0.7502, 0.2330, 0.8010],
         [0.3486, 0.5391, 0.0086, 0.1411, 0.8849]]])
previous shape: torch.Size([1, 3, 5])
tensor after squeezing: tensor([[0.3375, 0.9730, 0.9775, 0.7002, 0.4666],
        [0.9022, 0.7481, 0.7502, 0.2330, 0.8010],
        [0.3486, 0.5391, 0.0086, 0.1411, 0.8849]])
tensor shape after squeezing: torch.Size([3, 5])


In [ ]:
# torch unsqueeze -  adds a single dimension to a target tensor at a specific dimension
b_squeezed= b.squeeze()
print(f"previous tensor : {b_squeezed}")
print(f"previous shape: {b_squeezed.shape}")
#after unsqueezing
b_unsqueezed=b_squeezed.unsqueeze(dim=0)
print(f"\n new tensor :{b_unsqueezed}")
print(f"shape:{b_unsqueezed.shape}")

previous tensor : tensor([[0.3375, 0.9730, 0.9775, 0.7002, 0.4666],
        [0.9022, 0.7481, 0.7502, 0.2330, 0.8010],
        [0.3486, 0.5391, 0.0086, 0.1411, 0.8849]])
previous shape: torch.Size([3, 5])

 new tensor :tensor([[[0.3375, 0.9730, 0.9775, 0.7002, 0.4666],
         [0.9022, 0.7481, 0.7502, 0.2330, 0.8010],
         [0.3486, 0.5391, 0.0086, 0.1411, 0.8849]]])
shape:torch.Size([1, 3, 5])


In [ ]:
# torch.permute -  rearranges the dimensions of a target tensor in a specified order
x_original=torch.rand(size=(224,224,3))
#Permute the original tensor to rearrange the axis (or dim) order
x_permuted= x_original.permute(2,0,1) #shifts axia 0->1, 1->2 and 2->0
x_permuted.shape, x_original.shape

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [ ]:
y = torch.squeeze(x)
y,y.shape

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [ ]:
x=torch.rand(12,14,4)
y=x.permute(0,2,1)
x.shape,y.shape

(torch.Size([12, 14, 4]), torch.Size([12, 4, 14]))

In [ ]:
x[0,0,0],y[0,0,0]

(tensor(0.8903), tensor(0.8903))

In [ ]:
x[0,0,0]=0.4309

In [ ]:
x[0,0,0],y[0,0,0] # permute also shares the same memory as the original one and hence the value changes in y when x changes.

(tensor(0.4309), tensor(0.4309))

## Indexing (selecting data from tensor)
similar to numpy indexing

In [ ]:
import torch
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#indexing on our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#indexing on middle bracket
x[0][0] #same as x[0,0]

tensor([1, 2, 3])

In [ ]:
#indexing on the inner bracket
x[0][0][0]

tensor(1)

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
x[0,1,1]

tensor(5)

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
# we can use ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

## Pytorch and Numpy
* data in numpy, want in pytorch tensor ->`torch.from_numpy(ndarray)`
*Pytorch tensor -> numpy ->`torch.tensor.numpy`

In [ ]:
#numpy array to tensor
import torch
import numpy as np
array=np.arange(1.0,9.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy pytorch reflects numpy's default float64 dtype and not 32
array,tensor

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [ ]:
array.dtype #numpy default is float64

dtype('float64')

In [ ]:
array= array+1
array,tensor  #changing array doesnt change tensor

(array([2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [ ]:
# tensor to numpy
tensor= torch.ones(8)
tensor
numpy_tensor=tensor.numpy()
numpy_tensor,tensor,tensor.dtype

(array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 torch.float32)

In [ ]:
#change the tensor what happens to numpy tensor
tensor= tensor+1
tensor,numpy_tensor #remians the same

(tensor([2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take random out of random)

In short how neural net learns:

* `start with random numbers -> tensor operations -> update random numbers try to make them fit data -> again -> again..`
* to reduce the randomness pytorch comes with  the concept of random seed, essentially it flavours the `randomness`




In [ ]:
import torch

random_tensor_A =  torch.rand(3,4)
random_tensor_B= torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7509, 0.9190, 0.7429, 0.2238],
        [0.6368, 0.4699, 0.0752, 0.9304],
        [0.3474, 0.9667, 0.8198, 0.6124]])
tensor([[0.0990, 0.9125, 0.0862, 0.4016],
        [0.7903, 0.2594, 0.0330, 0.0619],
        [0.4611, 0.9538, 0.6729, 0.2139]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
 # let's make some random but reproducible
import torch
 # set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C =  torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D =  torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### reproducability
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed


## Running tensors and pytorch objects

1. GPU - Thanks to cuda + NVIDIA hardware + pytorch working behind
2. Use own gpu
3. Use cloud computing services-  AWS, Azure, GCP allows us to use computing resources on cloud

### since pytorch is capable of computing on gpu or cpu it's a best practice to set up device agnostic code
`Example : Run of GPU if available else CPU`

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
###  Check gpu access with pytorch
import torch
torch.cuda.is_available()

False

In [ ]:
# setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# count number of devices
torch.cuda.device_count()

0

### Putting tensors and models on gpu and cpu

In [ ]:
#create tensor
tensor= torch.tensor([1,2,3])
#its default on cpu
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#move it to gpu if required
tensor_gpu =  tensor.to(device)
tensor_gpu

tensor([1, 2, 3])

In [ ]:
 ### 4. moving tensors back to the cpu , if tensor on gpu we cant go Numpy
#  tensor_gpu.numpy()

In [ ]:
tensor_cpu=tensor_gpu.cpu()
tensor_cpu

tensor([1, 2, 3])

In [ ]:
numpy1= tensor_cpu.numpy()
numpy1

array([1, 2, 3])

###Exercises

In [ ]:
tensor= torch.rand(7,7)
tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [ ]:
tensor2=torch.rand(1,7)

In [ ]:
prod= torch.mm(tensor,tensor2.T)
prod, prod.shape

(tensor([[1.9625],
         [1.0950],
         [0.9967],
         [1.8910],
         [1.9205],
         [1.0674],
         [1.6949]]),
 torch.Size([7, 1]))

In [ ]:
RANDOMSEED=42
torch.manual_seed(RANDOMSEED)
tensor3=torch.rand(7,7)
torch.manual_seed(RANDOMSEED)
tensor4=torch.rand(1,7)
tensor3,tensor4

(tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
         [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
         [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
         [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
         [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566]]))

In [ ]:
prod2=tensor3.matmul(tensor4.T)
prod2,prod2.shape

(tensor([[3.2618],
         [3.4084],
         [2.4866],
         [1.4525],
         [1.7079],
         [2.7291],
         [2.9204]]),
 torch.Size([7, 1]))

In [ ]:
RANDOM_SEED=1234
torch.manual_seed(RANDOM_SEED)
tensor5=torch.rand(7,7).cuda()
torch.manual_seed(RANDOM_SEED)
tensor6=torch.rand(1,7).cuda()
tensor5,tensor6

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [ ]:
RANDOM_SEED=1234
torch.manual_seed(RANDOM_SEED)
tensor7=torch.rand(2,3).cuda()
torch.manual_seed(RANDOM_SEED)
tensor8=torch.rand(2,3).cuda()
tensor7,tensor8

In [ ]:
tensor7.device

In [ ]:
prod3=tensor7.matmul(tensor8.T)

In [ ]:
prod3,prod3.device

In [ ]:
torch.max(prod3)

In [ ]:
torch.min(prod3)

In [ ]:
torch.argmax(prod3)

In [ ]:
torch.argmin(prod3)

In [ ]:
tensor9=torch.rand(1,1,1,10)
tensor9

In [ ]:
tensor10=tensor9.squeeze()
tensor10